name: Update this repo's README with RSS Feed

on:
  schedule:
    # Once a day at 8 AM
    - cron: '0 8 * * *'
  workflow_dispatch: # This allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # This ensures the checkout action uses the GitHub token

      - name: Update README with RSS feed
        uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://sigmoidal.ai/en/feed/
          readme-section: feed
          max: 10
          template: "* [{{ title }}]({{ link }})\n"
          path: README.md
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use the provided GITHUB_TOKEN for authentication
          branch: main
